name: CI

on: push

env:
  DOWNLOAD_TOOL: curl -fLOSs --retry 2 --retry-delay 60

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Build
        working-directory: ${{ runner.workspace }}
        run: |
          mkdir build
          cd build
          cmake "$GITHUB_WORKSPACE" -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ${{ runner.workspace }}/build/kcchat
